import HeaderTop from "@/Components/Header";
import NavBAr from "@/Components/NavBAr";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hammers On Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderTop />
        <NavBAr />
      </main>
    </>
  );
}
